### ISSUE TITLE
How to handle multidimensional features in Copulas

### ISSUE THREAD

**Issue by dmey** [DAI-Lab/Copulas#109]
In the case where each feature sample contains a one- or multi- dimensional structure, can synthetic samples be generated using Copulas? 

Example where each feature is made up of 1D real-value arrays:

feature_01 | feature_02 |
-- | -- | 
[5.1, 5.1, 3.2] | [2.1, 5.1, 0.2]| 
[5.1, 4.1, 7.2] | [4.1, 3.1, 1.2]| 
[6.1, 5.3, 3.2] | [3.1, 5.1, 3.2]| 
...| ...

where the order of the array in each sample has a specific structure that needs to be preserved (e.g. a profile of something).

**Comment by csala** [comment]
Hi @dmey 

Unfortunately, this can not be directly passed to Copulas, as it only works with 2d matrices of numerical data.

But if the length of the vectors is known you can always covert the array values into columns before modeling and then back into arrays after sampling.

So instead of passing the table you shown to copulas, you would pass:

feature_01_1 | feature_01_2 | feature_01_3 | feature_02_1 | feature_02_2 | feature_02_3 |
-- | -- | -- | -- | -- | -- |
| 5.1 | 5.1 | 3.2 | 2.1 | 5.1 | 0.2 |
| 5.1 | 4.1 | 7.2 | 4.1 | 3.1 | 1.2 |
| 6.1 | 5.3 | 3.2 | 3.1 | 5.1 | 3.2 |
| ... | ... | ... | ... | ... | ... |

Would this be a solution?

**Comment by dmey** [comment]
Thanks @csala. I guess that that could be an option. My space is quite large (i.e. O(10) features, each with length O(100) so ~1,000 features using this method) and O(10^7) samples so that would make the space quite large.

I will give it a try with perhaps O(100) samples though and report back.

**Comment by dmey** [comment]
@csala I can confirm that this has worked --  I have only tried this on one single feature at the moment but splitting the vector into multiple features as suggested. 

One note/clarification I would like to make/ask is when creating synthetic samples from data that are not normally distributed. Understandably, using `copulas.multivariate.GaussianMultivariate` will create samples with symmetry from the mean even when the data are of arbitrary distributions. Would you have any suggestion for sampling data where features are multidimensional and where the distribution is non-Gaussian and different between each feature? BTW, this is kind of a different question so let me know if I can/should move it to a new issue...

**Comment by csala** [comment]
> @csala I can confirm that this has worked -- I have only tried this on one single feature at the moment but splitting the vector into multiple features as suggested.

Great! I'm glad to know that it worked :-)

Regarding the other topic, yes, it should be better to move it to a new issue, as this is actually a feature request, but I respond here anyway in advance.

This is a known limitation of Copulas at the moment: when using multivariate Copulas you can specify which univariate distribution to use, but you are limited to using the same one for all the variables.
This is something that we have had in mind for some time already, and one of the highest priority features to come in the next releases, but unfortunately its development has not been started yet.

**Comment by dmey** [comment]
Thanks! 👍

Q2 now moved to #110 and broken down into two parts to make it clearer.
