### ISSUE TITLE
fix numpy runtime warning

### ISSUE THREAD

**Issue by aliciasun** [DAI-Lab/Copulas#45]
### Description

Currently there are warnings in fit method that due to divided by zero. In that case, theta should be set to infinity and verify the computation is still correct for `get_pdf()`,`get_cdf()` etc. 

### Further Improvement
Maybe add a CopulaException class to ensure theta is in the valid range instead of checking inside each function.

**Comment by ManuelAlvarezC** [comment]
The problem showed up in the `Bivariate.select_colupas` method.

This method selects copulas by looking at how good their aproximations are based on the error they make against the empirical distribution of the original data.
This aproximation is calculated in the [0,1] range, and on both borders there are divisions by zero.

The implemented solution has been making the range slighty smaller, so the approximations are equally good but the warnings don't show up any more.

```python
base = np.linspace(0.0, 1.0, COMPUTE_EMPIRICAL_STEPS)
base = np.linspace(EPSILON, 1.0 - EPSILON, COMPUTE_EMPIRICAL_STEPS)
```
