### ISSUE TITLE
Matlab copulastat and copularnd equivalent 

### ISSUE THREAD

**Issue by lstorchi** [DAI-Lab/Copulas#72]
* Copulas version: origin/master
* Python version: 
* Operating System: Linux

### Description

Not being a copula's expert this is just quick question more then an issue . May I use copulas to 
fully emulate Matlab copulastat ? that is:

r = copulastat('Gaussian',rho) returns the Kendall’s rank correlation, r, that corresponds to a Gaussian copula with linear correlation parameters rho.

and the same apply to copularns:

u = copularnd('Gaussian',rho,n) returns n random vectors generated from a Gaussian copula with linear correlation parameters rho.

After searching it looks like there are  a couple of packages, Copulas and copualib to deal with 
Copula in python. Thus before starting working with one or the other would be good to have some feedback from the experts 

thanks

**Comment by ManuelAlvarezC** [comment]
Hi @lstorchi, and thanks for your questions,

I'm not Matlab expert, and the answers are based on what I've been able to grasp after reading the documentation of `copulastat` and `copularnd` modules, so please correct me if I'm wrong

> r = copulastat('Gaussian',rho) returns the Kendall’s rank correlation, r, that corresponds to a Gaussian copula with linear correlation parameters rho.

If I'm not mistaken, what you intend to do, can't  be done directly using our package, but can be done easily using [`pandas.DataFrame.corr`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html) directly on your raw data.

> u = copularnd('Gaussian',rho,n) returns n random vectors generated from a Gaussian copula with linear correlation parameters rho.

We have not implemented a way to sample from a copula passing directly the linear correlation parameters. What we do is compute the correlation from the raw data, and when sampling, we return the sampled values in the same space that the raw data.

However, as the gaussian copula is based on the Gaussian Multivariate distribution, you can archieve this by doing:

```python
import numpy as np

# We are assuming `rho` is your correlation parameters in a numpy.array
# We are assuming `n` is the number of vector you want to sample.

size = rho.shape[0]
means = np.zeros(size)
np.random.multivariate_normal(means, rho, size=n)
```

**Comment by lstorchi** [comment]
Dear Manuel 
   thanks, actually googling a bit I was able to find out almost the same,
and indeed I already implemented it some dais ago it in my to be cleaned 
minimal https://github.com/lstorchi/markovctheil/blob/master/copula_cli.py
copula CLI . 

thanks again
